### ISSUE TITLE
How to turn on syntax highlight?

### ISSUE THREAD

**Issue by Jie-Fang** [Freed-Wu/coc-mlir#2]
From my understanding, the mlir-lsp-server can provide lsp syntax highlight. But I couldn't show highlighting when I open an mlir file.

I have set `semanticTokens.enable=true` in the coc-settings.json. I don't install treesitter.

**Comment by Freed-Wu** [comment]
This project is ported from [vscode-mlir](https://github.com/llvm/vscode-mlir), which also doesn't support `semanticTokens.enable`. Perhaps we need to wait upstream to support it.

**Comment by Jie-Fang** [comment]
I found you had such highlighting from https://github.com/llvm/vscode-mlir/issues/5#issuecomment-1868998305.

How did you make it?

**Comment by Jie-Fang** [comment]
Do you know why the vscode supports mlir highlighting after installing the vscode-mlir?

BTW, I found clangd takes effects when I open `semanticTokens.enable`. So, you mean it needs extra effort for lsp-server to support semantic highlighting? 

I thought it's all about coc itself to support semantic highlighting, it looks like I'm wrong.

Another question: jumping definitions or declarations doesn't work at my side. I have checked the CocInfo and made sure the mlir-lsp-server had started.

**Comment by Freed-Wu** [comment]
> How did you make it?

In https://github.com/nvim-treesitter/nvim-treesitter :

> mlir (experimental, maintained by @artagnon)

> Do you know why the vscode supports mlir highlighting after installing the vscode-mlir?

I don't use vscode, sorry. I just know how to port vscode extension to vim :cry:

> I found clangd takes effects when I open semanticTokens.enable.

I guess what you want is syntax highlight not semantic highlight. tree-sitter and vim builtin `syntax/*.vim` provide syntax highlight, LSP provides semantic highlight. They are different things.

> jumping definitions or declarations doesn't work at my side

These features depend on langauge server. Not all features are supported by `mlir-lsp-server` currently. In fact, if one feature work, (such as diagnostic), we can ensure this extension work normally.

**Comment by Freed-Wu** [comment]
> Do you know why the vscode supports mlir highlighting after installing the vscode-mlir?

Oh, It seems to be related to tmLanguage.

neovim use vim syntax and tree-sitter to syntax highlight by default, vscode use textmate by default.

There is a neovim plugin to use textmate Language to syntax highlight <https://github.com/icedman/nvim-textmate>. Although I don't use it.
