### ISSUE TITLE
how to debug this extension?

### ISSUE THREAD

**Issue by pshung** [Freed-Wu/coc-mlir#3]
I have installed the extension. 
:CocInstall coc-mlir

However, when I open a ".mlir" file, auto-completion doesn't work at all. 

There's no error message in :CocInfo.

:CocList extensions 
shows coc-mlir is enabled. 

What can I do to debug this extension?
Thank you.

**Comment by Freed-Wu** [comment]
Perhaps <https://github.com/neoclide/coc.nvim/wiki/Debug-language-server> can work for you?

Remember `set ft=mlir`.

**Comment by pshung** [comment]
@Freed-Wu  what's the stable version of coc-mlir?   
:CocInstall coc-mlir  installs version of 0.0.2. 
It doesn't work well. 
should I upgrade to version of 0.0.10 ?

**Comment by Freed-Wu** [comment]
weird. can you see if mlir-lsp-server running?
```
ps auwx|grep mlir-lsp-server
```

**Comment by Freed-Wu** [comment]
> should I upgrade to version

Can you try latest version? Just `CocUpdate`.

**Comment by pshung** [comment]
update to version is 0.0.12rc1

first, the coc-mlir extension hasn't been activated automatically, just loaded. 
I activate it manually. 
I have configured mlir.server_path to my mlir-lsp-server
"mlir.server_path": "/home/work/MLIR/build/bin/mlir-lsp-server"

but mlir-lsp-server is not running. (both coclist services and ps |grep)
What can I do? Thank you.

**Comment by Freed-Wu** [comment]
do you `set ft=mlir`?

![Screenshot from 2024-03-20 10-36-36](https://github.com/Freed-Wu/coc-mlir/assets/32936898/89344067-f96e-4580-a25e-7b614e282c8e)

**Comment by pshung** [comment]
It works well after setting the file type to mlir. 
Thank you for your great project and help.
